import { Intent } from "../types";

export const INTENT_KEYWORDS: Record<Intent, string[]> = {
  [Intent.CONFERENCE]: [
    "conference",
    "mun",
    "delegate",
    "committee",
    "register",
    "registration",
    "venue",
    "date",
    "schedule",
    "fee",
    "cost",
    "price",
    "dress code",
    "accommodation",
    "capacity",
    "deadline",
    "award",
    "wear",
  ],
  [Intent.PROGRAM]: [
    "program",
    "programs",
    "training",
    "workshop",
    "diplomat",
    "bootcamp",
    "masterclass",
    "course",
    "learn",
  ],
  [Intent.ORGANIZATION]: [
    "about",
    "who are you",
    "smjmun",
    "history",
    "mission",
    "vision",
    "founder",
    "team",
    "core values",
    "objectives",
  ],
  [Intent.FAQ]: [
    "faq",
    "question",
    "help",
    "guidelines",
    "policy",
    "refund",
    "cancel",
  ],
  [Intent.CONTACT]: [
    "contact",
    "email",
    "phone",
    "whatsapp",
    "address",
    "reach",
    "support",
    "location",
  ],
  [Intent.GREETING]: [
    "hi",
    "hello",
    "hey",
    "greetings",
    "good morning",
    "good afternoon",
    "good evening",
    "start",
  ],
  [Intent.UNKNOWN]: [],
};
