import { defineField, defineType } from "sanity";

export const conference = defineType({
  name: "conference",
  title: "Conference",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "overview",
      title: "Overview",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "venue",
      title: "Venue",
      type: "string",
    }),
    defineField({
      name: "date",
      title: "Date",
      type: "datetime",
    }),
    defineField({
      name: "registrationFee",
      title: "Registration Fee (₹)",
      type: "number",
      validation: (rule) => rule.min(0),
      group: "registration",
    }),
    defineField({
      name: "capacity",
      title: "Capacity",
      type: "number",
      validation: (rule) => rule.min(0).integer(),
      group: "registration",
    }),
    defineField({
      name: "registrationOpen",
      title: "Registration Open",
      type: "boolean",
      initialValue: false,
      group: "registration",
    }),
    defineField({
      name: "registrationCloseDate",
      title: "Registration Close Date",
      type: "datetime",
      group: "registration",
    }),
    defineField({
      name: "registrationDeadline",
      title: "Registration Deadline",
      type: "datetime",
      group: "registration",
    }),
    defineField({
      name: "eligibility",
      title: "Eligibility",
      type: "string",
      group: "registration",
    }),
    defineField({
      name: "eligibilityRichText",
      title: "Eligibility (Rich Text)",
      type: "array",
      of: [{ type: "block" }],
      group: "registration",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: {
        list: [
          { title: "Draft", value: "draft" },
          { title: "Upcoming", value: "upcoming" },
          { title: "Live", value: "live" },
          { title: "Completed", value: "completed" },
        ],
        layout: "radio",
      },
      initialValue: "draft",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featured",
      title: "Featured",
      description: "Show this conference prominently on the homepage",
      type: "boolean",
      initialValue: false,
    }),
    defineField({
      name: "committees",
      title: "Committees",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({
              name: "name",
              title: "Committee Name",
              type: "string",
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: "agenda",
              title: "Agenda",
              type: "text",
              rows: 3,
            }),
            defineField({
              name: "chairperson",
              title: "Chairperson",
              type: "string",
            }),
          ],
          preview: {
            select: { title: "name", subtitle: "chairperson" },
          },
        },
      ],
    }),
    defineField({
      name: "agenda",
      title: "Detailed Agenda",
      type: "array",
      of: [{ type: "block" }],
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Alt Text",
              type: "string",
            }),
          ],
        },
      ],
    }),
    defineField({
      name: "dressCode",
      title: "Dress Code",
      type: "string",
      group: "logistics",
    }),
    defineField({
      name: "reportingTime",
      title: "Reporting Time",
      type: "string",
      group: "logistics",
    }),
    defineField({
      name: "accommodationAvailable",
      title: "Accommodation Available",
      type: "boolean",
      initialValue: false,
      group: "logistics",
    }),
    defineField({
      name: "foodProvided",
      title: "Food Provided",
      type: "boolean",
      initialValue: false,
      group: "logistics",
    }),
    defineField({
      name: "transportAvailable",
      title: "Transport Available",
      type: "boolean",
      initialValue: false,
      group: "logistics",
    }),
    defineField({
      name: "parkingAvailable",
      title: "Parking Available",
      type: "boolean",
      initialValue: false,
      group: "logistics",
    }),
    defineField({
      name: "certificateProvided",
      title: "Certificate Provided",
      type: "boolean",
      initialValue: false,
      group: "experience",
    }),
    defineField({
      name: "delegateKitIncluded",
      title: "Delegate Kit Included",
      type: "boolean",
      initialValue: false,
      group: "experience",
    }),
    defineField({
      name: "awards",
      title: "Awards",
      type: "array",
      of: [{ type: "string" }],
      group: "experience",
    }),
    defineField({
      name: "resources",
      title: "Resources",
      type: "array",
      of: [{ type: "resource" }],
      group: "resources",
    }),
    defineField({
      name: "refundPolicy",
      title: "Refund Policy",
      type: "text",
      group: "policies",
    }),
    defineField({
      name: "cancellationPolicy",
      title: "Cancellation Policy",
      type: "text",
      group: "policies",
    }),
    defineField({
      name: "codeOfConduct",
      title: "Code of Conduct",
      type: "text",
      group: "policies",
    }),
    defineField({
      name: "contact",
      title: "Conference Contact",
      type: "contactInfo",
      group: "contact",
    }),
    defineField({
      name: "seoTitle",
      title: "SEO Title",
      type: "string",
      description: "Override the default title for search engines",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "SEO Description",
      type: "text",
      rows: 3,
      description: "Meta description for search engines",
      group: "seo",
    }),
  ],
  groups: [
    { name: "registration", title: "Registration" },
    { name: "logistics", title: "Logistics" },
    { name: "experience", title: "Delegate Experience" },
    { name: "resources", title: "Resources" },
    { name: "policies", title: "Policies" },
    { name: "contact", title: "Contact" },
    { name: "seo", title: "SEO" },
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "status",
      media: "heroImage",
    },
  },
  orderings: [
    {
      title: "Date (Newest)",
      name: "dateDesc",
      by: [{ field: "date", direction: "desc" }],
    },
    {
      title: "Date (Oldest)",
      name: "dateAsc",
      by: [{ field: "date", direction: "asc" }],
    },
  ],
});
